sudo: required

language: c++

services:
  - docker

install:
  - FENICS_SHARED="/home/fenics/shared"
  - docker pull quay.io/fenicsproject/stable:latest

script:
  - docker run --rm -ti -v ${TRAVIS_BUILD_DIR}:${FENICS_SHARED} -w ${FENICS_SHARED} quay.io/fenicsproject/stable ${FENICS_SHARED}/run_test_in_docker.sh

